version: "3.4"
services:
  centos8libwebpbuild:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm8:/home/centos/rpmbuild/RPMS
    build:
      args:
        centos: 8
      context: .

volumes:
  rpms:
    name: rpms
  rpm8:
    name: rpm8
